# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Motel Walls
description: > # this means to ignore newlines until "baseurl:"
  A site to explore motel walls
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Markdown settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude: ["gulpfile.js", "package.json", "node_modules", "README.md", "src", "config", "Gemfile", "Gemfile.lock", "CNAME", "npm-debug.log"]

# Plugin settings
gems:
  - jekyll-feed
  - jekyll-sitemap
